---
- name: Ensure inventory directory exists
  ansible.builtin.file:
    path: "{{ persist_inventory_path }}"
    state: directory
    mode: "0777"
  delegate_to: localhost
  become: false

- name: Write persist resource to a file
  ansible.builtin.copy:
    content: "{{ persist_result_output }}"
    dest: "{{ persist_inventory_path }}/{{ persist_inventory_filename }}.{{ format | default('yaml') }}"
    mode: "0777"
  delegate_to: localhost
  become: false
